#!/bin/sh

top_link=$( awk '/## Doing/{ print NR; exit }' taskell.md )
bottom_link=$( awk '/## Done/{ print NR; exit }' taskell.md )

topper_link=$(( $top_link+1 ))
bottomer_link=$(( $bottom_link-1 ))

output=$( awk -v toplink="$topper_link" -v bottomlink="$bottomer_link" 'NR==toplink,NR==bottomlink{print $2}' taskell.md )

echo $output
