#! /bin/sh

sxhkd &
compton --config /home/jaomaloy/.config/compton/compton.conf -b &
$HOME/.config/polybar/launch.sh &

bspc monitor eDP-1 -d 1 2 3
bspc monitor DP-1 -d 4 5 6
# bspc monitor HDMI-1 -d 7 8 9

bspc config border_width                  0
bspc config window_gap                    8
bspc config top_padding                   0
bspc config bottom_padding                16
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config bottom_monocle_padding 8

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a firefoxdeveloperedition desktop='^4' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a St:explorer state=floating follow=on
bspc rule -a Zathura state=tiled follow=on focus=on
