#! /bin/sh

sxhkd &
feh --bg-scale $HOME/Data/Wallpapers/spiderman.png &
compton --config /home/jaomaloy/.config/compton/compton.conf -b &
$HOME/.config/polybar/launch.sh &

monitors=$(xrandr --listactivemonitors | grep "Monitors" | cut -d" " -f2)
if [[ $monitors == 1 ]]; then
    bspc monitor eDP-1 -d 1 2 3 4
elif [[ $monitors == 2 ]]; then
    bspc monitor eDP-1 -d 1 3 5
    bspc monitor DP-1 -d 2 4 6
else
    bspc monitor eDP-1 -d 1 2
    bspc monitor DP-1 -d 3 4
    bspc monitor HDMI-1 -d  5 6
fi

bspc config border_width                  0
bspc config window_gap                    8
bspc config top_padding                   0
bspc config bottom_padding                16
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config bottom_monocle_padding 8

bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a mpv desktop='^3' state=fullscreen follow=on
bspc rule -a St:development desktop='^1' state=tiled follow=on
bspc rule -a St:news desktop='^2' state=tiled follow=on
bspc rule -a St:music desktop='^3' state=tiled follow=on
bspc rule -a St:chat desktop='^2' state=tiled follow=on
bspc rule -a Zathura state=tiled follow=on focus=on
